-- CREATE

CREATE TABLE GUEST (
  PK NUMBER(7) NOT NULL,
  WNAME VARCHAR(30) NOT NULL,
  TITLE VARCHAR(100) NOT NULL,
  CONTENT VARCHAR(500) NOT NULL,
  PASSWD VARCHAR(10),
  WDATE DATE NOT NULL,
  VIEWCNT NUMBER(8) DEFAULT 0,
  PRIMARY KEY (PK)
);

SELECT * FROM GUEST;

-- INSERT

INSERT INTO GUEST(PK, WNAME, TITLE, CONTENT, PASSWD, WDATE) VALUES((SELECT NVL(MAX(PK), 0) FROM GUEST)+1, '배진오', '잘 보고 갑니다', '홈페이지 내용이 알차네요!', '1234', sysdate);

-- READ

SELECT PK, WNAME, TITLE, CONTENT, WDATE, VIEWCNT FROM GUEST WHERE PK = 1;

-- UPDATE

UPDATE GUEST SET WNAME='A', TITLE='B', CONTENT='C' WHERE PK = 1;

-- DELETE

DELETE GUEST WHERE PK = 1;

-- VIEWCNT

UPDATE GUEST SET VIEWCNT = VIEWCNT + 1 WHERE PK = 1;

-- PASSCHECK

SELECT PK FROM GUEST WHERE PK=1 AND PASSWD='1234';